### PR TITLE
add basic binary operators 

### PR DESCRIPTION
**Pull request by a8m**
Some of the basic operators, issue #10.
If this PR will approved I'll add the rest too.
Also, it could be great if you expand the README(contributions guidelines, usage, etc..) for this repo and for `cfg.js` too.

### CODE REVIEW

**Comment by indutny** [comment]
Very nice! I'm +1 on expanding README.md or adding CONTRIBUTING.md.

While we are here - may I ask you to make commit messages look like: `stub: add basic binary opereators` and in the commit body `Fix #10` ? ;)

**Comment by a8m** [comment]
@indutny cool!
commit message was updated.

**Comment by indutny** [comment]
Thank you! :) There are some minor typos, but I'll fix them.

**Comment by indutny** [comment]
Landed in 9edf4d4, thank you.

**Pull request closed without merging**
